spring:
  application:
    name: foodie-gateway
  redis:
    host: 127.0.0.1
    port: 6379
    #password: imooc
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#          lower-case-service-id: false
  main:
    allow-bean-definition-overriding: true
  zipkin:
    discovery-client-enabled: true
    base-url: http://ZIPKIN-SERVER/
  sleuth:
    sampler:
      probability: 1

server:
  port: 20004

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/

## 开启所有actuator-endpoint
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
