server:
  port: 10002

spring:
  shardingsphere:
    datasource:
      names: master,slave0
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/foodie-user?useUnicode=true&autoReconnect=true&serverTimezone=UTC
        username: root
        password: 123456
      slave0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/foodie-user-slave?useUnicode=true&autoReconnect=true&serverTimezone=UTC
        username: root
        password: 123456
    sharding:
      master-slave-rules:
        ms:
          master-data-source-name: master
          slave-data-source-names: slave0
    props:
      sql:
        show: true

  zipkin:
    discovery-client-enabled: true
    base-url: http://ZIPKIN-SERVER/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

redisson:
  address: redis://192.168.1.105:6379
  password: imooc

## 开启所有actuator-endpoint - 配置中心
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

hystrix:
  command:
    default:
      fallback:
        enabled: true
      circuitBreaker:
        enabled: true
        # 超过50%错误，那么开启熔断
        errorThresholdPercentage: 50
        # 5个request之后才进行统计
        requestVolumeThreshold: 5
        # 10秒之后进入半开状态
        sleepWindowInMilliseconds: 10000
      #是否开启超时设置
      execution:
        timeout:
          enabled: true
        # 可以指定隔离方式是线程池还是信号量
        isolation:
          thread:
            # 发生超时是是否中断，默认true
            interruptOnTimeout: true
            interruptOnFutureCancel: true
            timeoutInMilliseconds: 4000
    loginFail:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000