spring:
  application:
    name: zipkin-server
  main:
    allow-bean-definition-overriding: true

server:
  port: 20005

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.104:20000/eureka/
    registry-fetch-interval-seconds: 5 #eureka client刷新本地缓存时间，默认30
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 7  #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己），默认90
    lease-renewal-interval-in-seconds: 5   #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则），默认30

management:
  metrics:
    web:
      server:
        # 关闭自动检测请求
        auto-time-requests: false
